services:
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080
    restart: always

  back:
    build: .
    container_name: back
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./back:/app

  front:
    build: .
    container_name: front
    depends_on:
      - back
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./front:/app

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
