services:
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080
    restart: always

  back:
    build: .
    container_name: back
    depends_on:
      - db
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    volumes:
      - ./back:/app

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
