import React from 'react';
import withProtection from '@/hoc/withProtection';

function Home() {
	return (
		<div>
			<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tristique eleifend erat, eget dictum sem varius vitae. Maecenas feugiat mauris eget nisl tempor, a porta odio malesuada. Sed quis quam nec ex hendrerit auctor vitae eget dui. Nulla varius suscipit risus, in eleifend ipsum euismod in. Sed condimentum dapibus risus, eu molestie metus dictum nec. Donec ipsum diam, maximus at sapien ut, efficitur semper nulla. Mauris in pellentesque mi. Praesent lectus eros, pellentesque in leo eget, imperdiet eleifend lorem. Pellentesque quis finibus erat. Suspendisse hendrerit egestas ipsum, in sagittis nisl rhoncus sed. Pellentesque purus ante, dictum ut tortor sit amet, cursus ultrices quam. Pellentesque diam neque, vestibulum vitae imperdiet sed, porttitor ut orci. Suspendisse potenti. Morbi mollis eros ut libero vehicula eleifend.

In fringilla vitae nisi sed ornare. Aliquam vel scelerisque lorem. Morbi eu purus in ligula facilisis dapibus consectetur nec justo. Integer non pellentesque lacus, quis fringilla enim. In condimentum ornare risus nec mattis. Suspendisse tristique, nisi at egestas aliquam, mi libero euismod lacus, nec rutrum elit nulla at felis. Praesent scelerisque suscipit elit vel gravida. Nullam consequat mattis est sed tincidunt. Nunc cursus ultricies velit, at interdum lacus pretium non. Fusce vel venenatis dolor.

Duis id condimentum elit. Suspendisse viverra ante sed leo vehicula aliquam. Ut et imperdiet mi. Sed finibus ultrices consectetur. Suspendisse ut turpis condimentum, tristique sapien vel, rutrum nibh. Sed mollis gravida ante. Nullam eu nisl fermentum, consectetur tellus ac, eleifend enim. Maecenas dignissim purus eu neque venenatis viverra. Vestibulum in lorem sed arcu consequat tempus ac nec metus. Mauris placerat dapibus purus ac vulputate. Donec sagittis dui sed placerat lacinia. Praesent id orci quis ante lobortis semper sit amet vel nisi. Donec ut turpis convallis, vestibulum magna vitae, dictum lectus.

Aliquam erat volutpat. Nam molestie ligula quis erat volutpat aliquet id a odio. Sed nunc velit, varius in pretium eget, vulputate ut dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vestibulum ipsum quis congue facilisis. Fusce facilisis massa nec lectus convallis, lobortis imperdiet erat placerat. Fusce sit amet erat in libero euismod tincidunt eget quis diam. Aliquam eu gravida lacus, et elementum odio. Sed arcu ipsum, mattis sed interdum ut, imperdiet finibus quam. Mauris nibh orci, porttitor non felis vitae, volutpat finibus urna.

Curabitur dapibus et sapien eleifend semper. Morbi aliquet at nunc mollis fringilla. Etiam sit amet ipsum metus. Morbi varius scelerisque ipsum et faucibus. Praesent quis nisl gravida eros consectetur congue. Phasellus suscipit eget tellus vitae tincidunt. Cras interdum vulputate nunc, consequat ullamcorper tortor commodo id. Praesent gravida accumsan lectus, quis feugiat purus pretium sed. Phasellus convallis, urna vel convallis efficitur, dui dolor suscipit mauris, vel rutrum purus sapien at erat. In sit amet imperdiet massa. Mauris ut ex nisl. Quisque eu lectus metus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tristique eleifend erat, eget dictum sem varius vitae. Maecenas feugiat mauris eget nisl tempor, a porta odio malesuada. Sed quis quam nec ex hendrerit auctor vitae eget dui. Nulla varius suscipit risus, in eleifend ipsum euismod in. Sed condimentum dapibus risus, eu molestie metus dictum nec. Donec ipsum diam, maximus at sapien ut, efficitur semper nulla. Mauris in pellentesque mi. Praesent lectus eros, pellentesque in leo eget, imperdiet eleifend lorem. Pellentesque quis finibus erat. Suspendisse hendrerit egestas ipsum, in sagittis nisl rhoncus sed. Pellentesque purus ante, dictum ut tortor sit amet, cursus ultrices quam. Pellentesque diam neque, vestibulum vitae imperdiet sed, porttitor ut orci. Suspendisse potenti. Morbi mollis eros ut libero vehicula eleifend.

In fringilla vitae nisi sed ornare. Aliquam vel scelerisque lorem. Morbi eu purus in ligula facilisis dapibus consectetur nec justo. Integer non pellentesque lacus, quis fringilla enim. In condimentum ornare risus nec mattis. Suspendisse tristique, nisi at egestas aliquam, mi libero euismod lacus, nec rutrum elit nulla at felis. Praesent scelerisque suscipit elit vel gravida. Nullam consequat mattis est sed tincidunt. Nunc cursus ultricies velit, at interdum lacus pretium non. Fusce vel venenatis dolor.

Duis id condimentum elit. Suspendisse viverra ante sed leo vehicula aliquam. Ut et imperdiet mi. Sed finibus ultrices consectetur. Suspendisse ut turpis condimentum, tristique sapien vel, rutrum nibh. Sed mollis gravida ante. Nullam eu nisl fermentum, consectetur tellus ac, eleifend enim. Maecenas dignissim purus eu neque venenatis viverra. Vestibulum in lorem sed arcu consequat tempus ac nec metus. Mauris placerat dapibus purus ac vulputate. Donec sagittis dui sed placerat lacinia. Praesent id orci quis ante lobortis semper sit amet vel nisi. Donec ut turpis convallis, vestibulum magna vitae, dictum lectus.

Aliquam erat volutpat. Nam molestie ligula quis erat volutpat aliquet id a odio. Sed nunc velit, varius in pretium eget, vulputate ut dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vestibulum ipsum quis congue facilisis. Fusce facilisis massa nec lectus convallis, lobortis imperdiet erat placerat. Fusce sit amet erat in libero euismod tincidunt eget quis diam. Aliquam eu gravida lacus, et elementum odio. Sed arcu ipsum, mattis sed interdum ut, imperdiet finibus quam. Mauris nibh orci, porttitor non felis vitae, volutpat finibus urna.

Curabitur dapibus et sapien eleifend semper. Morbi aliquet at nunc mollis fringilla. Etiam sit amet ipsum metus. Morbi varius scelerisque ipsum et faucibus. Praesent quis nisl gravida eros consectetur congue. Phasellus suscipit eget tellus vitae tincidunt. Cras interdum vulputate nunc, consequat ullamcorper tortor commodo id. Praesent gravida accumsan lectus, quis feugiat purus pretium sed. Phasellus convallis, urna vel convallis efficitur, dui dolor suscipit mauris, vel rutrum purus sapien at erat. In sit amet imperdiet massa. Mauris ut ex nisl. Quisque eu lectus metus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tristique eleifend erat, eget dictum sem varius vitae. Maecenas feugiat mauris eget nisl tempor, a porta odio malesuada. Sed quis quam nec ex hendrerit auctor vitae eget dui. Nulla varius suscipit risus, in eleifend ipsum euismod in. Sed condimentum dapibus risus, eu molestie metus dictum nec. Donec ipsum diam, maximus at sapien ut, efficitur semper nulla. Mauris in pellentesque mi. Praesent lectus eros, pellentesque in leo eget, imperdiet eleifend lorem. Pellentesque quis finibus erat. Suspendisse hendrerit egestas ipsum, in sagittis nisl rhoncus sed. Pellentesque purus ante, dictum ut tortor sit amet, cursus ultrices quam. Pellentesque diam neque, vestibulum vitae imperdiet sed, porttitor ut orci. Suspendisse potenti. Morbi mollis eros ut libero vehicula eleifend.

In fringilla vitae nisi sed ornare. Aliquam vel scelerisque lorem. Morbi eu purus in ligula facilisis dapibus consectetur nec justo. Integer non pellentesque lacus, quis fringilla enim. In condimentum ornare risus nec mattis. Suspendisse tristique, nisi at egestas aliquam, mi libero euismod lacus, nec rutrum elit nulla at felis. Praesent scelerisque suscipit elit vel gravida. Nullam consequat mattis est sed tincidunt. Nunc cursus ultricies velit, at interdum lacus pretium non. Fusce vel venenatis dolor.

Duis id condimentum elit. Suspendisse viverra ante sed leo vehicula aliquam. Ut et imperdiet mi. Sed finibus ultrices consectetur. Suspendisse ut turpis condimentum, tristique sapien vel, rutrum nibh. Sed mollis gravida ante. Nullam eu nisl fermentum, consectetur tellus ac, eleifend enim. Maecenas dignissim purus eu neque venenatis viverra. Vestibulum in lorem sed arcu consequat tempus ac nec metus. Mauris placerat dapibus purus ac vulputate. Donec sagittis dui sed placerat lacinia. Praesent id orci quis ante lobortis semper sit amet vel nisi. Donec ut turpis convallis, vestibulum magna vitae, dictum lectus.

Aliquam erat volutpat. Nam molestie ligula quis erat volutpat aliquet id a odio. Sed nunc velit, varius in pretium eget, vulputate ut dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vestibulum ipsum quis congue facilisis. Fusce facilisis massa nec lectus convallis, lobortis imperdiet erat placerat. Fusce sit amet erat in libero euismod tincidunt eget quis diam. Aliquam eu gravida lacus, et elementum odio. Sed arcu ipsum, mattis sed interdum ut, imperdiet finibus quam. Mauris nibh orci, porttitor non felis vitae, volutpat finibus urna.

Curabitur dapibus et sapien eleifend semper. Morbi aliquet at nunc mollis fringilla. Etiam sit amet ipsum metus. Morbi varius scelerisque ipsum et faucibus. Praesent quis nisl gravida eros consectetur congue. Phasellus suscipit eget tellus vitae tincidunt. Cras interdum vulputate nunc, consequat ullamcorper tortor commodo id. Praesent gravida accumsan lectus, quis feugiat purus pretium sed. Phasellus convallis, urna vel convallis efficitur, dui dolor suscipit mauris, vel rutrum purus sapien at erat. In sit amet imperdiet massa. Mauris ut ex nisl. Quisque eu lectus metus.</span>
		</div>
	);
}

export default withProtection(Home, { authenticated: true, fallback: '/signin' });